export enum DocumentType {
  DRIVING_LICENSE = 'permis_conduire',
  SAFETY_DIPLOMA = 'diplome_securite',
  ID_DOCUMENT_RECTO = 'piece_identite_recto',
  ID_DOCUMENT_VERSO = 'piece_identite_verso',
  INSURANCE = 'assurance',
  MAINTENANCE_REPORT = 'rapport_maintenance',
  WEIGHING_TICKET = 'bon_pesage',
  FUEL_RECEIPT = 'facture_carburant',
  INCIDENT_REPORT = 'rapport_incident',
  COMPANY_LOGO = 'logo',
  USER_PROFILE_PICTURE = 'photo_profil_utilisateur',
  PAYMENT_FICHE = 'payment_fiche',
  JOB_CONTRACT = 'job_contract',
  MEDICAL_STOP = 'medical_stop',
  MEDICAL_VISIT = 'medical_visit',
  SELFIE = 'selfie',
  PERMIS_RECTO = 'permis_recto',
  PERMIS_VERSO = 'permis_verso'
}
